###
# @name signup

POST http://localhost:3003/signup
Content-Type: application/json

{
   "name": "joao" ,
   "email": "joao@gmail.com" ,
   "password": "123456"
}

###
# @name login
POST http://localhost:3003/login
Content-Type: application/json

{
   "email": "joao@gmail.com" ,
   "password": "123456"
}

###
# @token = {{login.response.body.token}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZhNzZhNmYwLTk1ZGYtNGZkMy1iODVlLWIyMTFiNTc1ZTI4MyIsImlhdCI6MTY1NjUzNTA3NSwiZXhwIjoxNjU2NTM2Mjc1fQ.NGu8X-1Fs6RCKnl6U1Y4NCYQw-tJvEot3qF44k9HOR
GET http://localhost:3003/user/profile
Authorization: {{token}}
###

@id = aa477ba9-4ef8-40a5-ad04-275b27f23d08

GET http://localhost:3003/user/{{id}}
Authorization: {{token}}
###