###
# @name signup
# Create User
POST http://localhost:3003/signup
Content-Type: application/json

{
   "name": "matheus" ,
   "email": "matheus@gmail.com" ,
   "password": "123456"
}

###
# @name login
# Login 
POST http://localhost:3003/login
Content-Type: application/json

{
   "email": "matheus@gmail.com" ,
   "password": "123456"
}

###
@token = {{ login.response.body.token }}
# Post 
POST http://localhost:3003/post
Content-Type: application/json
Authorization: {{token}}

{
   "photo": "link da foto" ,
   "description": "Carnaval no Rio",
   "date": "20/03/1999",
   "role": "evento"
}

###
@token = {{ login.response.body.token }}

@id = 0bae13e0-1e4e-4dbd-ad59-059985cd038b
# Pegar Post por ID 
GET  http://localhost:3003/post/{{id}}
Authorization: {{token}}


###
@token = {{ login.response.body.token }}

# Seguir usuário 
PUT  http://localhost:3003/user/follow
Content-Type: application/json
Authorization: {{token}}

{
   "id": "ef2efe9a-860e-46e8-8fbb-2f89b2cf0201"
}

###
@token = {{ login.response.body.token }}

# Parar de seguir usuário 
DELETE  http://localhost:3003/user/unfollow
Content-Type: application/json
Authorization: {{token}}

{
   "id": "1dbdce1b-44ea-49db-aeb5-c233e90816e9"
}
###
@token = {{ login.response.body.token }}

# Pegar post que usuário segue
GET  http://localhost:3003/user/posts
Authorization: {{token}}

###
@token = {{ login.response.body.token }}

# Pegar Post por Type
GET  http://localhost:3003/user/normal
Authorization: {{token}}


