###
# @name signup
# Create User
POST http://localhost:3003/signup
Content-Type: application/json

{
   "name": "renan" ,
   "email": "renan@gmail.com" ,
   "password": "123456"
}

###
# @name login
# Login 
POST http://localhost:3003/login
Content-Type: application/json

{
   "email": "joao@gmail.com" ,
   "password": "123456"
}

###
@token = {{ login.response.body.token }}
# Post 
POST http://localhost:3003/post
Content-Type: application/json
Authorization: {{token}}

{
   "photo": "link da foto" ,
   "description": "Antiga foto de SP",
   "date": "10/10/1942",
   "role": "normal"
}

###
@token = {{ login.response.body.token }}

@id = 0bae13e0-1e4e-4dbd-ad59-059985cd038b
# Pegar Post por ID 
GET  http://localhost:3003/post/{{id}}
Authorization: {{token}}


###
@token = {{ login.response.body.token }}

# Seguir usuário 
PUT  http://localhost:3003/user/follow
Content-Type: application/json
Authorization: {{token}}

{
   "id": "1dbdce1b-44ea-49db-aeb5-c233e90816e9"
}

###
@token = {{ login.response.body.token }}

# Parar de seguir usuário 
DELETE  http://localhost:3003/user/unfollow
Content-Type: application/json
Authorization: {{token}}

{
   "id": "1dbdce1b-44ea-49db-aeb5-c233e90816e9"
}


