POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name":"Marcos",
    "email":"marcos@gmail.com",
    "password":"123456",
    "role":"NORMAL"
}


###
# @name login
POST http://localhost:3003/login 
Content-Type: application/json

{
    "email": "renan@gmail.com", 
    "password": "123456"
}

###
@token = {{login.response.body.token}}
GET http://localhost:3003/all 
Authorization: {{token}}

###