POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name":"Renan",
    "email":"renan@gmail.com",
    "password":"123456",
    "role":"ADMIN"
}


###
POST http://localhost:3003/login 
Content-Type: application/json

{
    "email": "renan@gmail.com", 
    "password": "123456"
}
