# Criar usuário 
POST http://localhost:3003/user/create
Content-Type: application/json

{
    "first_name": "Jorge",
    "last_name": "Santos",
    "participation": 10
}

###
# Pegar usuário
GET http://localhost:3003/user

###
# Deletar usuário

@id = cd344938-ecbb-4ff4-b34a-0af226d37515
DELETE http://localhost:3003/user/delete/{{id}}